from __future__ import annotations

import tomllib
from pathlib import Path

import click
import pytest
from rich.text import Text
from typer.testing import CliRunner

from codex_converter.cli import _build_report_table, app
from codex_converter.discovery import discover
from codex_converter.models import ReportEntry, Status
from codex_converter.safety import contained_path, reject_user_claude_path


runner = CliRunner()
HELP_ENV = {"COLUMNS": "120"}


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def make_fixture(root: Path) -> None:
    write(root / "CLAUDE.md", "Root instructions\n")
    write(root / "pkg" / "CLAUDE.md", "Nested instructions\n")
    write(root / ".claude" / "skills" / "review" / "SKILL.md", "# Review\n")
    write(root / ".claude" / "skills" / "review" / "references" / "notes.md", "notes\n")
    write(root / ".claude" / "commands" / "ship.md", "Ship it\n")
    write(
        root / ".claude" / "agents" / "planner.md",
        "---\nname: planner\ndescription: Plans small tasks.\n---\nPlan carefully.\n",
    )
    write(root / ".claude" / "settings.json", '{"hooks": {}, "permissions": {"allow": []}}')
    write(root / ".claude" / "settings.local.json", "{}")


def test_root_help_exits_successfully() -> None:
    result = runner.invoke(app, ["--help"], env=HELP_ENV)
    output = click.unstyle(result.output)

    assert result.exit_code == 0
    assert "Version: dev" in output
    assert "--version" in output
    assert "inspect" in output
    assert "convert" in output
    assert "clean" in output


def test_version_exits_successfully() -> None:
    result = runner.invoke(app, ["--version"])

    assert result.exit_code == 0
    assert result.output == "codex-converter dev\n"


def test_inspect_help_exits_successfully() -> None:
    result = runner.invoke(app, ["inspect", "--help"], env=HELP_ENV)
    output = click.unstyle(result.output)

    assert result.exit_code == 0
    assert "Claude Code project directory to inspect" in output


def test_convert_help_exits_successfully() -> None:
    result = runner.invoke(app, ["convert", "--help"], env=HELP_ENV)
    output = click.unstyle(result.output)

    assert result.exit_code == 0
    assert "--dry-run" in output
    assert "--force" in output
    assert "--include-local-settings" in output
    assert "--gitignore" in output


def test_clean_help_exits_successfully() -> None:
    result = runner.invoke(app, ["clean", "--help"], env=HELP_ENV)
    output = click.unstyle(result.output)

    assert result.exit_code == 0
    assert "TARGET" in output
    assert "--dry-run" in output
    assert "--force" in output


def test_inspect_default_source_is_current_directory() -> None:
    with runner.isolated_filesystem():
        cwd = Path.cwd().resolve()

        result = runner.invoke(app, ["inspect"])

        assert result.exit_code == 0
        assert f"Inspecting {cwd}" in result.output


def test_discovery_finds_project_assets(tmp_path: Path) -> None:
    make_fixture(tmp_path)

    entries = discover(tmp_path)
    found = {(entry.kind, entry.source.relative_to(tmp_path).as_posix(), entry.status.value) for entry in entries}

    assert ("instructions", "CLAUDE.md", "convertible") in found
    assert ("instructions", "pkg/CLAUDE.md", "convertible") in found
    assert ("skill", ".claude/skills/review/SKILL.md", "convertible") in found
    assert ("command", ".claude/commands/ship.md", "convertible") in found
    assert ("agent", ".claude/agents/planner.md", "convertible") in found
    assert ("settings.local", ".claude/settings.local.json", "skipped") in found
    assert ("settings.hooks", ".claude/settings.json", "unsupported") in found


def test_rejects_user_scoped_claude_source() -> None:
    with pytest.raises(ValueError):
        reject_user_claude_path(Path.home() / ".claude", "source")


def test_output_path_traversal_is_blocked(tmp_path: Path) -> None:
    with pytest.raises(ValueError):
        contained_path(tmp_path, tmp_path / ".." / "escape.txt")


def test_convert_dry_run_writes_no_files(tmp_path: Path) -> None:
    make_fixture(tmp_path)

    result = runner.invoke(app, ["convert", str(tmp_path), "--dry-run"])

    assert result.exit_code == 0
    assert "planned" in result.output
    assert not (tmp_path / "AGENTS.md").exists()
    assert not (tmp_path / ".codex").exists()
    assert not (tmp_path / ".agents").exists()


def test_convert_creates_expected_tree(tmp_path: Path) -> None:
    make_fixture(tmp_path)

    result = runner.invoke(app, ["convert", str(tmp_path)])

    assert result.exit_code == 0
    assert (tmp_path / "AGENTS.md").read_text().startswith(
        "<!-- Generated by codex-converter from CLAUDE.md -->"
    )
    assert (tmp_path / "pkg" / "AGENTS.md").exists()
    skill = tmp_path / ".agents" / "skills" / "review"
    assert "name: review" in (skill / "SKILL.md").read_text()
    assert "description: Converted Claude skill review." in (skill / "SKILL.md").read_text()
    assert (skill / "references" / "notes.md").read_text() == "notes\n"
    assert "<!-- Generated by codex-converter from .claude/skills/review/SKILL.md -->" in (
        skill / "SKILL.md"
    ).read_text()
    command_skill = (tmp_path / ".agents" / "skills" / "ship" / "SKILL.md").read_text()
    assert "name: ship" in command_skill
    assert "<!-- Generated by codex-converter from .claude/commands/ship.md -->" in command_skill
    agent = tomllib.loads((tmp_path / ".codex" / "agents" / "planner.toml").read_text())
    assert agent["name"] == "planner"
    assert agent["description"] == "Plans small tasks."
    assert agent["developer_instructions"] == "Plan carefully.\n"
    tomllib.loads((tmp_path / ".codex" / "config.toml").read_text())


def test_default_conversion_skips_local_settings(tmp_path: Path) -> None:
    write(tmp_path / ".claude" / "settings.json", '{"permissions": {"allow": ["base"]}}')
    write(tmp_path / ".claude" / "settings.local.json", '{"permissions": {"allow": ["local"]}}')

    result = runner.invoke(app, ["convert", str(tmp_path)])

    assert result.exit_code == 0
    assert "settings.local" in result.output
    assert "skipped" in result.output
    config = tomllib.loads((tmp_path / ".codex" / "config.toml").read_text())
    assert config["codex_converter"]["claude_settings"]["permissions"]["allow"] == ["base"]


def test_include_local_settings_merges_recursively(tmp_path: Path) -> None:
    write(
        tmp_path / ".claude" / "settings.json",
        '{"permissions": {"allow": ["base"], "deny": ["keep"]}, "scalar": "base"}',
    )
    write(
        tmp_path / ".claude" / "settings.local.json",
        '{"permissions": {"allow": ["local"]}, "scalar": false, "localOnly": 3}',
    )

    result = runner.invoke(app, ["convert", str(tmp_path), "--include-local-settings"])

    assert result.exit_code == 0
    config = tomllib.loads((tmp_path / ".codex" / "config.toml").read_text())
    settings = config["codex_converter"]["claude_settings"]
    assert settings["permissions"]["allow"] == ["local"]
    assert settings["permissions"]["deny"] == ["keep"]
    assert settings["scalar"] is False
    assert settings["localOnly"] == 3


def test_invalid_settings_json_reports_error_without_config(tmp_path: Path) -> None:
    write(tmp_path / ".claude" / "settings.json", "{")

    result = runner.invoke(app, ["convert", str(tmp_path)])

    assert result.exit_code == 0
    assert "invalid JSON" in result.output
    assert not (tmp_path / ".codex" / "config.toml").exists()


def test_invalid_local_settings_json_reports_error_when_included(tmp_path: Path) -> None:
    write(tmp_path / ".claude" / "settings.json", "{}")
    write(tmp_path / ".claude" / "settings.local.json", "{")

    result = runner.invoke(app, ["convert", str(tmp_path), "--include-local-settings"])

    assert result.exit_code == 0
    assert "invalid JSON" in result.output
    assert not (tmp_path / ".codex" / "config.toml").exists()


def test_generated_config_toml_keeps_lines_under_120_characters(tmp_path: Path) -> None:
    values = ", ".join(f'"item-{index:02d}"' for index in range(20))
    write(tmp_path / ".claude" / "settings.json", f'{{"permissions": {{"allow": [{values}]}}}}')

    result = runner.invoke(app, ["convert", str(tmp_path)])

    assert result.exit_code == 0
    content = (tmp_path / ".codex" / "config.toml").read_text()
    tomllib.loads(content)
    assert max(len(line) for line in content.splitlines()) <= 120


@pytest.mark.parametrize(
    ("status", "style"),
    [
        (Status.WRITTEN, "green"),
        (Status.PLANNED, "cyan"),
        (Status.CONVERTIBLE, "cyan"),
        (Status.SKIPPED, "yellow"),
        (Status.UNSUPPORTED, "magenta"),
        (Status.CONFLICT, "red"),
        (Status.ERROR, "bold red"),
    ],
)
def test_report_status_cells_have_rich_styles(status: Status, style: str) -> None:
    table = _build_report_table(
        [ReportEntry("kind", Path("source"), status, "detail")],
        Path("."),
    )
    status_cell = table.columns[0]._cells[0]

    assert isinstance(status_cell, Text)
    assert str(status_cell) == status.value
    assert status_cell.style == style


def test_report_table_uses_column_styles_without_changing_cell_text() -> None:
    table = _build_report_table(
        [ReportEntry("kind", Path("source"), Status.ERROR, "detail", Path("target"))],
        Path("."),
    )

    assert table.title_style == "bold white"
    assert table.header_style == "bold"
    assert table.border_style == "dim"
    assert table.columns[1].style == "cyan"
    assert table.columns[2].style == "bright_cyan"
    assert table.columns[3].style == "green"
    assert table.columns[4].style == "dim white"
    assert table.columns[1]._cells[0] == "kind"
    assert table.columns[2]._cells[0] == "source"
    assert table.columns[3]._cells[0] == "target"
    assert table.columns[4]._cells[0] == "detail"


def test_report_output_remains_plain_text_readable(tmp_path: Path) -> None:
    write(tmp_path / "CLAUDE.md", "Root instructions\n")

    result = runner.invoke(app, ["convert", str(tmp_path), "--dry-run"])
    output = click.unstyle(result.output)

    assert result.exit_code == 0
    assert "\x1b[" in result.output
    assert "planned" in output


def test_config_report_details_distinguish_default_and_settings(tmp_path: Path) -> None:
    default = runner.invoke(app, ["convert", str(tmp_path), "--dry-run"])
    assert default.exit_code == 0
    assert "created default Codex project config" in default.output

    write(tmp_path / ".claude" / "settings.json", '{"permissions": {"allow": []}}')
    settings = runner.invoke(app, ["convert", str(tmp_path), "--dry-run"])
    assert settings.exit_code == 0
    assert "converted Claude settings to reviewable Codex config" in settings.output


def test_gitignore_flag_creates_gitignore_with_generated_paths(tmp_path: Path) -> None:
    make_fixture(tmp_path)

    result = runner.invoke(app, ["convert", str(tmp_path), "--gitignore"])

    assert result.exit_code == 0
    assert (tmp_path / ".gitignore").read_text().splitlines() == [
        "AGENTS.md",
        ".agents/",
        ".codex/",
        "pkg/AGENTS.md",
    ]


def test_gitignore_flag_preserves_existing_content_and_avoids_duplicates(tmp_path: Path) -> None:
    make_fixture(tmp_path)
    write(tmp_path / ".gitignore", "dist/\nAGENTS.md\n")

    first = runner.invoke(app, ["convert", str(tmp_path), "--gitignore"])
    second = runner.invoke(app, ["convert", str(tmp_path), "--gitignore", "--force"])

    assert first.exit_code == 0
    assert second.exit_code == 0
    assert (tmp_path / ".gitignore").read_text().splitlines().count("AGENTS.md") == 1
    assert "dist/" in (tmp_path / ".gitignore").read_text().splitlines()


def test_gitignore_dry_run_writes_nothing(tmp_path: Path) -> None:
    make_fixture(tmp_path)

    result = runner.invoke(app, ["convert", str(tmp_path), "--gitignore", "--dry-run"])

    assert result.exit_code == 0
    assert "planned" in result.output
    assert not (tmp_path / ".gitignore").exists()


def test_gitignore_uses_output_directory(tmp_path: Path) -> None:
    source = tmp_path / "source"
    output = tmp_path / "output"
    make_fixture(source)

    result = runner.invoke(app, ["convert", str(source), "--output", str(output), "--gitignore"])

    assert result.exit_code == 0
    assert (output / ".gitignore").exists()
    assert not (source / ".gitignore").exists()


def test_convert_without_gitignore_does_not_modify_gitignore(tmp_path: Path) -> None:
    make_fixture(tmp_path)

    result = runner.invoke(app, ["convert", str(tmp_path)])

    assert result.exit_code == 0
    assert not (tmp_path / ".gitignore").exists()


def test_clean_dry_run_reports_removals_and_leaves_files(tmp_path: Path) -> None:
    make_fixture(tmp_path)
    assert runner.invoke(app, ["convert", str(tmp_path)]).exit_code == 0

    result = runner.invoke(app, ["clean", str(tmp_path), "--dry-run"])

    assert result.exit_code == 0
    assert "planned" in result.output
    assert (tmp_path / "AGENTS.md").exists()
    assert (tmp_path / ".codex" / "config.toml").exists()


def test_clean_removes_generated_outputs_and_preserves_source(tmp_path: Path) -> None:
    make_fixture(tmp_path)
    assert runner.invoke(app, ["convert", str(tmp_path), "--gitignore"]).exit_code == 0

    result = runner.invoke(app, ["clean", str(tmp_path)])

    assert result.exit_code == 0
    assert not (tmp_path / "AGENTS.md").exists()
    assert not (tmp_path / "pkg" / "AGENTS.md").exists()
    assert not (tmp_path / ".codex" / "config.toml").exists()
    assert not (tmp_path / ".codex" / "agents" / "planner.toml").exists()
    assert not (tmp_path / ".agents" / "skills" / "review").exists()
    assert (tmp_path / "CLAUDE.md").exists()
    assert (tmp_path / ".gitignore").read_text() == ""


def test_clean_preserves_unmarked_files_without_force(tmp_path: Path) -> None:
    write(tmp_path / "AGENTS.md", "User-authored instructions\n")

    result = runner.invoke(app, ["clean", str(tmp_path)])

    assert result.exit_code == 0
    assert (tmp_path / "AGENTS.md").exists()
    assert "skipped" in result.output


def test_clean_force_removes_unmarked_known_target(tmp_path: Path) -> None:
    write(tmp_path / "AGENTS.md", "User-authored instructions\n")

    result = runner.invoke(app, ["clean", str(tmp_path), "--force"])

    assert result.exit_code == 0
    assert not (tmp_path / "AGENTS.md").exists()


def test_clean_preserves_non_empty_generated_parent_directories(tmp_path: Path) -> None:
    make_fixture(tmp_path)
    assert runner.invoke(app, ["convert", str(tmp_path)]).exit_code == 0
    write(tmp_path / ".codex" / "agents" / "manual.toml", "name = \"manual\"\n")

    result = runner.invoke(app, ["clean", str(tmp_path)])

    assert result.exit_code == 0
    assert (tmp_path / ".codex" / "agents").exists()
    assert (tmp_path / ".codex" / "agents" / "manual.toml").exists()


def test_clean_removes_generated_gitignore_entries_only(tmp_path: Path) -> None:
    make_fixture(tmp_path)
    assert runner.invoke(app, ["convert", str(tmp_path), "--gitignore"]).exit_code == 0
    with (tmp_path / ".gitignore").open("a") as handle:
        handle.write("dist/\n")

    result = runner.invoke(app, ["clean", str(tmp_path)])

    assert result.exit_code == 0
    assert (tmp_path / ".gitignore").read_text() == "dist/\n"


def test_clean_rejects_user_scoped_claude_path() -> None:
    result = runner.invoke(app, ["clean", str(Path.home() / ".claude")])

    assert result.exit_code != 0
    assert "user-scoped Claude path" in click.unstyle(result.output)


def test_convert_reports_conflicts_without_force(tmp_path: Path) -> None:
    make_fixture(tmp_path)
    first = runner.invoke(app, ["convert", str(tmp_path)])
    assert first.exit_code == 0

    second = runner.invoke(app, ["convert", str(tmp_path)])

    assert second.exit_code == 0
    assert "conflict" in second.output


def test_convert_force_updates_generated_outputs(tmp_path: Path) -> None:
    make_fixture(tmp_path)
    first = runner.invoke(app, ["convert", str(tmp_path)])
    assert first.exit_code == 0
    write(tmp_path / "CLAUDE.md", "Updated instructions\n")

    second = runner.invoke(app, ["convert", str(tmp_path), "--force"])

    assert second.exit_code == 0
    assert "Updated instructions" in (tmp_path / "AGENTS.md").read_text()


def test_agent_missing_description_is_reported(tmp_path: Path) -> None:
    write(tmp_path / ".claude" / "agents" / "broken.md", "---\nname: broken\n---\nBody\n")

    result = runner.invoke(app, ["convert", str(tmp_path)])

    assert result.exit_code == 0
    assert "missing required description" in result.output
    assert not (tmp_path / ".codex" / "agents" / "broken.toml").exists()


def test_agent_invalid_yaml_is_reported(tmp_path: Path) -> None:
    write(tmp_path / ".claude" / "agents" / "broken.md", "---\nname: [\n---\nBody\n")

    result = runner.invoke(app, ["convert", str(tmp_path)])

    assert result.exit_code == 0
    assert "invalid YAML frontmatter" in result.output
