from __future__ import annotations

import tomllib
from pathlib import Path

import pytest
from typer.testing import CliRunner

from codex_converter.cli import app
from codex_converter.discovery import discover
from codex_converter.safety import contained_path, reject_user_claude_path


runner = CliRunner()


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def make_fixture(root: Path) -> None:
    write(root / "CLAUDE.md", "Root instructions\n")
    write(root / "pkg" / "CLAUDE.md", "Nested instructions\n")
    write(root / ".claude" / "skills" / "review" / "SKILL.md", "# Review\n")
    write(root / ".claude" / "skills" / "review" / "references" / "notes.md", "notes\n")
    write(root / ".claude" / "commands" / "ship.md", "Ship it\n")
    write(
        root / ".claude" / "agents" / "planner.md",
        "---\nname: planner\ndescription: Plans small tasks.\n---\nPlan carefully.\n",
    )
    write(root / ".claude" / "settings.json", '{"hooks": {}, "permissions": {"allow": []}}')
    write(root / ".claude" / "settings.local.json", "{}")


def test_root_help_exits_successfully() -> None:
    result = runner.invoke(app, ["--help"])

    assert result.exit_code == 0
    assert "inspect" in result.output
    assert "convert" in result.output


def test_inspect_help_exits_successfully() -> None:
    result = runner.invoke(app, ["inspect", "--help"])

    assert result.exit_code == 0
    assert "Claude Code project directory to inspect" in result.output


def test_convert_help_exits_successfully() -> None:
    result = runner.invoke(app, ["convert", "--help"])

    assert result.exit_code == 0
    assert "--dry-run" in result.output
    assert "--force" in result.output


def test_inspect_default_source_is_current_directory() -> None:
    with runner.isolated_filesystem():
        cwd = Path.cwd().resolve()

        result = runner.invoke(app, ["inspect"])

        assert result.exit_code == 0
        assert f"Inspecting {cwd}" in result.output


def test_discovery_finds_project_assets(tmp_path: Path) -> None:
    make_fixture(tmp_path)

    entries = discover(tmp_path)
    found = {(entry.kind, entry.source.relative_to(tmp_path).as_posix(), entry.status.value) for entry in entries}

    assert ("instructions", "CLAUDE.md", "convertible") in found
    assert ("instructions", "pkg/CLAUDE.md", "convertible") in found
    assert ("skill", ".claude/skills/review/SKILL.md", "convertible") in found
    assert ("command", ".claude/commands/ship.md", "convertible") in found
    assert ("agent", ".claude/agents/planner.md", "convertible") in found
    assert ("settings.local", ".claude/settings.local.json", "skipped") in found
    assert ("settings.hooks", ".claude/settings.json", "unsupported") in found


def test_rejects_user_scoped_claude_source() -> None:
    with pytest.raises(ValueError):
        reject_user_claude_path(Path.home() / ".claude", "source")


def test_output_path_traversal_is_blocked(tmp_path: Path) -> None:
    with pytest.raises(ValueError):
        contained_path(tmp_path, tmp_path / ".." / "escape.txt")


def test_convert_dry_run_writes_no_files(tmp_path: Path) -> None:
    make_fixture(tmp_path)

    result = runner.invoke(app, ["convert", str(tmp_path), "--dry-run"])

    assert result.exit_code == 0
    assert "planned" in result.output
    assert not (tmp_path / "AGENTS.md").exists()
    assert not (tmp_path / ".codex").exists()
    assert not (tmp_path / ".agents").exists()


def test_convert_creates_expected_tree(tmp_path: Path) -> None:
    make_fixture(tmp_path)

    result = runner.invoke(app, ["convert", str(tmp_path)])

    assert result.exit_code == 0
    assert (tmp_path / "AGENTS.md").read_text().startswith(
        "<!-- Generated by codex-converter from CLAUDE.md -->"
    )
    assert (tmp_path / "pkg" / "AGENTS.md").exists()
    skill = tmp_path / ".agents" / "skills" / "review"
    assert "name: review" in (skill / "SKILL.md").read_text()
    assert "description: Converted Claude skill review." in (skill / "SKILL.md").read_text()
    assert (skill / "references" / "notes.md").read_text() == "notes\n"
    assert "name: ship" in (tmp_path / ".agents" / "skills" / "ship" / "SKILL.md").read_text()
    agent = tomllib.loads((tmp_path / ".codex" / "agents" / "planner.toml").read_text())
    assert agent["name"] == "planner"
    assert agent["description"] == "Plans small tasks."
    assert agent["developer_instructions"] == "Plan carefully.\n"
    tomllib.loads((tmp_path / ".codex" / "config.toml").read_text())


def test_convert_reports_conflicts_without_force(tmp_path: Path) -> None:
    make_fixture(tmp_path)
    first = runner.invoke(app, ["convert", str(tmp_path)])
    assert first.exit_code == 0

    second = runner.invoke(app, ["convert", str(tmp_path)])

    assert second.exit_code == 0
    assert "conflict" in second.output


def test_convert_force_updates_generated_outputs(tmp_path: Path) -> None:
    make_fixture(tmp_path)
    first = runner.invoke(app, ["convert", str(tmp_path)])
    assert first.exit_code == 0
    write(tmp_path / "CLAUDE.md", "Updated instructions\n")

    second = runner.invoke(app, ["convert", str(tmp_path), "--force"])

    assert second.exit_code == 0
    assert "Updated instructions" in (tmp_path / "AGENTS.md").read_text()


def test_agent_missing_description_is_reported(tmp_path: Path) -> None:
    write(tmp_path / ".claude" / "agents" / "broken.md", "---\nname: broken\n---\nBody\n")

    result = runner.invoke(app, ["convert", str(tmp_path)])

    assert result.exit_code == 0
    assert "missing required description" in result.output
    assert not (tmp_path / ".codex" / "agents" / "broken.toml").exists()


def test_agent_invalid_yaml_is_reported(tmp_path: Path) -> None:
    write(tmp_path / ".claude" / "agents" / "broken.md", "---\nname: [\n---\nBody\n")

    result = runner.invoke(app, ["convert", str(tmp_path)])

    assert result.exit_code == 0
    assert "invalid YAML frontmatter" in result.output

