from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

import tomli_w
import yaml

from .discovery import discover
from .frontmatter import build_frontmatter, split_frontmatter
from .models import ReportEntry, Status
from .safety import contained_path, reject_user_claude_path

HEADER = "<!-- Generated by codex-converter from {source} -->\n\n"
TOML_HEADER = "# Generated by codex-converter from {source}.\n"
GENERATED_MARKER = "Generated by codex-converter"
GITIGNORE_BASE_ENTRIES = ("AGENTS.md", ".agents/", ".codex/")


def convert(
    source: Path,
    output: Path | None,
    *,
    dry_run: bool,
    force: bool,
    include_local_settings: bool = False,
    update_gitignore: bool = False,
) -> list[ReportEntry]:
    source = reject_user_claude_path(source, "source")
    output = reject_user_claude_path(output or source, "output")
    entries = discover(source, include_local_settings=include_local_settings)
    results: list[ReportEntry] = []

    for entry in entries:
        if entry.status != Status.CONVERTIBLE:
            results.append(entry)
            continue
        if entry.kind == "instructions":
            results.append(_convert_instruction(source, output, entry.source, dry_run=dry_run, force=force))
        elif entry.kind == "skill":
            results.extend(_convert_skill(source, output, entry.source, dry_run=dry_run, force=force))
        elif entry.kind == "command":
            results.append(_convert_command(source, output, entry.source, dry_run=dry_run, force=force))
        elif entry.kind == "agent":
            results.append(_convert_agent(source, output, entry.source, dry_run=dry_run, force=force))
        elif entry.kind == "settings":
            results.append(
                _convert_config(
                    source,
                    output,
                    include_local_settings=include_local_settings,
                    dry_run=dry_run,
                    force=force,
                )
            )
        elif entry.kind == "settings.local" and not (source / ".claude" / "settings.json").exists():
            results.append(
                _convert_config(
                    source,
                    output,
                    include_local_settings=include_local_settings,
                    dry_run=dry_run,
                    force=force,
                )
            )

    if not any(entry.kind in {"settings", "settings.local"} and entry.status == Status.CONVERTIBLE for entry in entries):
        results.append(
            _convert_config(
                source,
                output,
                include_local_settings=include_local_settings,
                dry_run=dry_run,
                force=force,
            )
        )

    if update_gitignore:
        results.append(_update_gitignore(source, output, entries, dry_run=dry_run))

    return results


def clean(target: Path, *, dry_run: bool, force: bool) -> list[ReportEntry]:
    target = reject_user_claude_path(target, "target")
    results: list[ReportEntry] = []

    paths: list[Path] = []
    root_agents = target / "AGENTS.md"
    if root_agents.exists():
        paths.append(root_agents)
    paths.extend(sorted(path for path in target.rglob("AGENTS.md") if path != root_agents))
    paths.extend(sorted((target / ".codex" / "agents").glob("*.toml")))
    config = target / ".codex" / "config.toml"
    if config.exists():
        paths.append(config)

    for path in paths:
        path = contained_path(target, path)
        if _has_generated_marker(path) or force:
            results.append(_remove_file(target, path, dry_run=dry_run))
        else:
            results.append(ReportEntry("clean", path, Status.SKIPPED, "missing codex-converter generated marker", path))

    skills_dir = target / ".agents" / "skills"
    if skills_dir.is_dir():
        for skill_dir in sorted(path for path in skills_dir.iterdir() if path.is_dir()):
            skill_file = skill_dir / "SKILL.md"
            if force or _has_generated_marker(skill_file):
                results.append(_remove_tree(target, skill_dir, dry_run=dry_run))
            else:
                results.append(
                    ReportEntry("clean", skill_dir, Status.SKIPPED, "missing codex-converter generated marker", skill_dir)
                )

    gitignore = target / ".gitignore"
    if gitignore.exists():
        gitignore_result = _clean_gitignore(target, gitignore, dry_run=dry_run)
        if gitignore_result is not None:
            results.append(gitignore_result)

    for directory in (
        target / ".codex" / "agents",
        target / ".codex",
        target / ".agents" / "skills",
        target / ".agents",
    ):
        if directory.is_dir() and not any(directory.iterdir()):
            results.append(_remove_dir(target, directory, dry_run=dry_run))

    if not results:
        results.append(ReportEntry("clean", target, Status.SKIPPED, "no generated codex-converter output found", target))
    return results


def _write_text(
    source: Path,
    target: Path,
    content: str,
    kind: str,
    detail: str,
    *,
    output: Path,
    dry_run: bool,
    force: bool,
) -> ReportEntry:
    target = contained_path(output, target)
    if target.exists() and not force:
        return ReportEntry(kind, source, Status.CONFLICT, "target exists; use --force to overwrite", target)
    if dry_run:
        return ReportEntry(kind, source, Status.PLANNED, detail, target)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    return ReportEntry(kind, source, Status.WRITTEN, detail, target)


def _convert_instruction(source_root: Path, output: Path, source: Path, *, dry_run: bool, force: bool) -> ReportEntry:
    relative_dir = source.relative_to(source_root).parent
    target = output / relative_dir / "AGENTS.md"
    rel_source = source.relative_to(source_root)
    content = HEADER.format(source=rel_source.as_posix()) + source.read_text()
    return _write_text(
        source,
        target,
        content,
        "instructions",
        "converted CLAUDE.md to AGENTS.md",
        output=output,
        dry_run=dry_run,
        force=force,
    )


def _convert_skill(source_root: Path, output: Path, skill_md: Path, *, dry_run: bool, force: bool) -> list[ReportEntry]:
    skill_dir = skill_md.parent
    name = skill_dir.name
    target_dir = output / ".agents" / "skills" / name
    target_skill = target_dir / "SKILL.md"
    target_skill = contained_path(output, target_skill)
    if target_dir.exists() and not force:
        return [ReportEntry("skill", skill_md, Status.CONFLICT, "target skill directory exists; use --force", target_dir)]
    if dry_run:
        return [ReportEntry("skill", skill_md, Status.PLANNED, "copy skill directory", target_dir)]

    shutil.copytree(skill_dir, target_dir, dirs_exist_ok=True)
    rel_source = skill_md.relative_to(source_root)
    _normalize_skill_file(target_skill, name, rel_source.as_posix())
    return [ReportEntry("skill", skill_md, Status.WRITTEN, "copied skill directory", target_dir)]


def _convert_command(source_root: Path, output: Path, command: Path, *, dry_run: bool, force: bool) -> ReportEntry:
    name = command.stem
    target = output / ".agents" / "skills" / name / "SKILL.md"
    body = command.read_text()
    rel_source = command.relative_to(source_root)
    content = build_frontmatter(
        {"name": name, "description": f"Converted Claude command {name}."},
        HEADER.format(source=rel_source.as_posix()) + body,
    )
    return _write_text(
        command,
        target,
        content,
        "command",
        "converted command to skill",
        output=output,
        dry_run=dry_run,
        force=force,
    )


def _convert_agent(source_root: Path, output: Path, agent: Path, *, dry_run: bool, force: bool) -> ReportEntry:
    try:
        metadata, body, has_frontmatter = split_frontmatter(agent.read_text())
    except yaml.YAMLError as exc:
        return ReportEntry("agent", agent, Status.ERROR, f"invalid YAML frontmatter: {exc}")
    except ValueError as exc:
        return ReportEntry("agent", agent, Status.ERROR, str(exc))
    if not has_frontmatter:
        return ReportEntry("agent", agent, Status.ERROR, "missing YAML frontmatter")
    name = _string_value(metadata, "name") or agent.stem
    description = _string_value(metadata, "description")
    if not description:
        return ReportEntry("agent", agent, Status.ERROR, "missing required description")
    if not body.strip():
        return ReportEntry("agent", agent, Status.ERROR, "missing developer instructions body")
    data = {
        "name": name,
        "description": description,
        "developer_instructions": body.strip() + "\n",
    }
    target = output / ".codex" / "agents" / f"{agent.stem}.toml"
    rel_source = agent.relative_to(source_root)
    return _write_text(
        agent,
        target,
        TOML_HEADER.format(source=rel_source.as_posix()) + tomli_w.dumps(data),
        "agent",
        "converted agent to TOML",
        output=output,
        dry_run=dry_run,
        force=force,
    )


def _convert_config(
    source_root: Path,
    output: Path,
    *,
    include_local_settings: bool,
    dry_run: bool,
    force: bool,
) -> ReportEntry:
    settings = source_root / ".claude" / "settings.json"
    local_settings = source_root / ".claude" / "settings.local.json"
    loaded = _load_settings(settings, local_settings, include_local_settings=include_local_settings)
    if isinstance(loaded, ReportEntry):
        return loaded
    data, source_label = loaded
    content = _settings_config_toml(data, source_label, include_local_settings=include_local_settings)
    detail = (
        "converted Claude settings to reviewable Codex config"
        if data
        else "created default Codex project config"
    )
    return _write_text(
        settings if settings.exists() else source_root,
        output / ".codex" / "config.toml",
        content,
        "config",
        detail,
        output=output,
        dry_run=dry_run,
        force=force,
    )


def _normalize_skill_file(path: Path, name: str, source: str) -> None:
    metadata, body, _ = split_frontmatter(path.read_text())
    changed = False
    if not _string_value(metadata, "name"):
        metadata["name"] = name
        changed = True
    if not _string_value(metadata, "description"):
        metadata["description"] = f"Converted Claude skill {name}."
        changed = True
    if GENERATED_MARKER not in body:
        body = HEADER.format(source=source) + body
        changed = True
    if changed or not path.read_text().startswith("---\n"):
        path.write_text(build_frontmatter(metadata, body))


def _string_value(data: dict[str, Any], key: str) -> str | None:
    value = data.get(key)
    return value if isinstance(value, str) and value.strip() else None


def _load_settings(
    settings: Path, local_settings: Path, *, include_local_settings: bool
) -> tuple[dict[str, Any], str] | ReportEntry:
    data: dict[str, Any] = {}
    source_label = "default project config"
    if settings.exists():
        loaded = _read_json_object(settings, "settings")
        if isinstance(loaded, ReportEntry):
            return loaded
        data = loaded
        source_label = ".claude/settings.json"
    if include_local_settings and local_settings.exists():
        loaded = _read_json_object(local_settings, "settings.local")
        if isinstance(loaded, ReportEntry):
            return loaded
        data = _merge_settings(data, loaded)
        source_label = (
            ".claude/settings.json + .claude/settings.local.json"
            if settings.exists()
            else ".claude/settings.local.json"
        )
    return data, source_label


def _read_json_object(path: Path, kind: str) -> dict[str, Any] | ReportEntry:
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        return ReportEntry(kind, path, Status.ERROR, f"invalid JSON: {exc.msg}")
    if not isinstance(data, dict):
        return ReportEntry(kind, path, Status.ERROR, "settings file must contain a JSON object")
    return data


def _merge_settings(base: dict[str, Any], local: dict[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, local_value in local.items():
        base_value = merged.get(key)
        if isinstance(base_value, dict) and isinstance(local_value, dict):
            merged[key] = _merge_settings(base_value, local_value)
        else:
            merged[key] = local_value
    return merged


def _settings_config_toml(data: dict[str, Any], source: str, *, include_local_settings: bool) -> str:
    config: dict[str, Any] = {
        "codex_converter": {
            "source": source,
            "include_local_settings": include_local_settings,
        }
    }
    if data:
        config["codex_converter"]["claude_settings"] = data
    return TOML_HEADER.format(source=source) + _toml_dumps(config)


def _toml_dumps(data: dict[str, Any]) -> str:
    lines: list[str] = []
    _write_toml_table(lines, [], data)
    return "\n".join(lines).rstrip() + "\n"


def _write_toml_table(lines: list[str], prefix: list[str], data: dict[str, Any]) -> None:
    scalars: dict[str, Any] = {}
    tables: dict[str, dict[str, Any]] = {}
    for key, value in data.items():
        if isinstance(value, dict):
            tables[key] = value
        else:
            scalars[key] = value
    if prefix:
        lines.append(f"[{'.'.join(_toml_key(part) for part in prefix)}]")
    for key, value in scalars.items():
        lines.append(f"{_toml_key(key)} = {_toml_value(value)}")
    for key, value in tables.items():
        if lines and lines[-1] != "":
            lines.append("")
        _write_toml_table(lines, [*prefix, key], value)


def _toml_key(key: str) -> str:
    if key and key.replace("_", "").replace("-", "").isalnum() and key[0].isalpha():
        return key
    return json.dumps(key)


def _toml_value(value: Any) -> str:
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value).lower()
    if value is None:
        return '""'
    if isinstance(value, list):
        inline = "[" + ", ".join(_toml_value(item) for item in value) + "]"
        if len(inline) <= 80 and "\n" not in inline:
            return inline
        items = [f"    {_toml_value(item)}," for item in value]
        return "[\n" + "\n".join(items) + "\n]"
    return json.dumps(str(value))


def _update_gitignore(source: Path, output: Path, entries: list[ReportEntry], *, dry_run: bool) -> ReportEntry:
    wanted = list(GITIGNORE_BASE_ENTRIES)
    for entry in entries:
        if entry.kind == "instructions" and entry.status == Status.CONVERTIBLE:
            relative_dir = entry.source.relative_to(source).parent
            if relative_dir != Path("."):
                wanted.append((relative_dir / "AGENTS.md").as_posix())
    gitignore = output / ".gitignore"
    existing = gitignore.read_text().splitlines() if gitignore.exists() else []
    existing_set = {line.strip() for line in existing}
    missing = [item for item in dict.fromkeys(wanted) if item not in existing_set]
    if not missing:
        return ReportEntry("gitignore", gitignore, Status.SKIPPED, "generated paths already present", gitignore)
    detail = "add generated output paths to .gitignore: " + ", ".join(missing)
    if dry_run:
        return ReportEntry("gitignore", gitignore, Status.PLANNED, detail, gitignore)
    gitignore.parent.mkdir(parents=True, exist_ok=True)
    prefix = "" if not existing or gitignore.read_text().endswith("\n") else "\n"
    with gitignore.open("a") as handle:
        handle.write(prefix)
        for item in missing:
            handle.write(f"{item}\n")
    return ReportEntry("gitignore", gitignore, Status.WRITTEN, detail, gitignore)


def _has_generated_marker(path: Path) -> bool:
    return path.is_file() and GENERATED_MARKER in path.read_text(errors="ignore")


def _remove_file(target: Path, path: Path, *, dry_run: bool) -> ReportEntry:
    if dry_run:
        return ReportEntry("clean", path, Status.PLANNED, "remove generated file", path)
    path.unlink()
    return ReportEntry("clean", path, Status.WRITTEN, "removed generated file", path)


def _remove_tree(target: Path, path: Path, *, dry_run: bool) -> ReportEntry:
    path = contained_path(target, path)
    if dry_run:
        return ReportEntry("clean", path, Status.PLANNED, "remove generated directory", path)
    shutil.rmtree(path)
    return ReportEntry("clean", path, Status.WRITTEN, "removed generated directory", path)


def _remove_dir(target: Path, path: Path, *, dry_run: bool) -> ReportEntry:
    path = contained_path(target, path)
    if dry_run:
        return ReportEntry("clean", path, Status.PLANNED, "remove empty generated directory", path)
    path.rmdir()
    return ReportEntry("clean", path, Status.WRITTEN, "removed empty generated directory", path)


def _clean_gitignore(target: Path, gitignore: Path, *, dry_run: bool) -> ReportEntry | None:
    lines = gitignore.read_text().splitlines()
    generated = set(GITIGNORE_BASE_ENTRIES)
    generated.update(path.relative_to(target).as_posix() for path in target.rglob("AGENTS.md"))
    kept = [line for line in lines if line.strip() not in generated and not line.strip().endswith("/AGENTS.md")]
    if kept == lines:
        return None
    if dry_run:
        return ReportEntry("clean", gitignore, Status.PLANNED, "remove generated .gitignore entries", gitignore)
    gitignore.write_text("\n".join(kept).rstrip() + ("\n" if kept else ""))
    return ReportEntry("clean", gitignore, Status.WRITTEN, "removed generated .gitignore entries", gitignore)
