from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

import tomli_w
import yaml

from .discovery import discover
from .frontmatter import build_frontmatter, split_frontmatter
from .models import ReportEntry, Status
from .safety import contained_path, reject_user_claude_path

HEADER = "<!-- Generated by codex-converter from {source} -->\n\n"


def convert(source: Path, output: Path | None, *, dry_run: bool, force: bool) -> list[ReportEntry]:
    source = reject_user_claude_path(source, "source")
    output = reject_user_claude_path(output or source, "output")
    entries = discover(source)
    results: list[ReportEntry] = []

    for entry in entries:
        if entry.status != Status.CONVERTIBLE:
            results.append(entry)
            continue
        if entry.kind == "instructions":
            results.append(_convert_instruction(source, output, entry.source, dry_run=dry_run, force=force))
        elif entry.kind == "skill":
            results.extend(_convert_skill(source, output, entry.source, dry_run=dry_run, force=force))
        elif entry.kind == "command":
            results.append(_convert_command(source, output, entry.source, dry_run=dry_run, force=force))
        elif entry.kind == "agent":
            results.append(_convert_agent(source, output, entry.source, dry_run=dry_run, force=force))
        elif entry.kind == "settings":
            results.append(_convert_config(output, entry.source, dry_run=dry_run, force=force))

    if not any(entry.kind == "settings" for entry in entries):
        results.append(_convert_config(output, source / ".claude" / "settings.json", dry_run=dry_run, force=force))

    return results


def _write_text(
    source: Path,
    target: Path,
    content: str,
    kind: str,
    detail: str,
    *,
    output: Path,
    dry_run: bool,
    force: bool,
) -> ReportEntry:
    target = contained_path(output, target)
    if target.exists() and not force:
        return ReportEntry(kind, source, Status.CONFLICT, "target exists; use --force to overwrite", target)
    if dry_run:
        return ReportEntry(kind, source, Status.PLANNED, detail, target)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    return ReportEntry(kind, source, Status.WRITTEN, detail, target)


def _convert_instruction(source_root: Path, output: Path, source: Path, *, dry_run: bool, force: bool) -> ReportEntry:
    relative_dir = source.relative_to(source_root).parent
    target = output / relative_dir / "AGENTS.md"
    rel_source = source.relative_to(source_root)
    content = HEADER.format(source=rel_source.as_posix()) + source.read_text()
    return _write_text(
        source,
        target,
        content,
        "instructions",
        "converted CLAUDE.md to AGENTS.md",
        output=output,
        dry_run=dry_run,
        force=force,
    )


def _convert_skill(source_root: Path, output: Path, skill_md: Path, *, dry_run: bool, force: bool) -> list[ReportEntry]:
    skill_dir = skill_md.parent
    name = skill_dir.name
    target_dir = output / ".agents" / "skills" / name
    target_skill = target_dir / "SKILL.md"
    target_skill = contained_path(output, target_skill)
    if target_dir.exists() and not force:
        return [ReportEntry("skill", skill_md, Status.CONFLICT, "target skill directory exists; use --force", target_dir)]
    if dry_run:
        return [ReportEntry("skill", skill_md, Status.PLANNED, "copy skill directory", target_dir)]

    shutil.copytree(skill_dir, target_dir, dirs_exist_ok=True)
    _normalize_skill_file(target_skill, name)
    return [ReportEntry("skill", skill_md, Status.WRITTEN, "copied skill directory", target_dir)]


def _convert_command(source_root: Path, output: Path, command: Path, *, dry_run: bool, force: bool) -> ReportEntry:
    name = command.stem
    target = output / ".agents" / "skills" / name / "SKILL.md"
    body = command.read_text()
    content = build_frontmatter(
        {"name": name, "description": f"Converted Claude command {name}."},
        body,
    )
    return _write_text(
        command,
        target,
        content,
        "command",
        "converted command to skill",
        output=output,
        dry_run=dry_run,
        force=force,
    )


def _convert_agent(source_root: Path, output: Path, agent: Path, *, dry_run: bool, force: bool) -> ReportEntry:
    try:
        metadata, body, has_frontmatter = split_frontmatter(agent.read_text())
    except yaml.YAMLError as exc:
        return ReportEntry("agent", agent, Status.ERROR, f"invalid YAML frontmatter: {exc}")
    except ValueError as exc:
        return ReportEntry("agent", agent, Status.ERROR, str(exc))
    if not has_frontmatter:
        return ReportEntry("agent", agent, Status.ERROR, "missing YAML frontmatter")
    name = _string_value(metadata, "name") or agent.stem
    description = _string_value(metadata, "description")
    if not description:
        return ReportEntry("agent", agent, Status.ERROR, "missing required description")
    if not body.strip():
        return ReportEntry("agent", agent, Status.ERROR, "missing developer instructions body")
    data = {
        "name": name,
        "description": description,
        "developer_instructions": body.strip() + "\n",
    }
    target = output / ".codex" / "agents" / f"{agent.stem}.toml"
    return _write_text(
        agent,
        target,
        tomli_w.dumps(data),
        "agent",
        "converted agent to TOML",
        output=output,
        dry_run=dry_run,
        force=force,
    )


def _convert_config(output: Path, settings: Path, *, dry_run: bool, force: bool) -> ReportEntry:
    content = "# Generated by codex-converter.\n"
    return _write_text(
        settings,
        output / ".codex" / "config.toml",
        content,
        "config",
        "created default Codex project config",
        output=output,
        dry_run=dry_run,
        force=force,
    )


def _normalize_skill_file(path: Path, name: str) -> None:
    metadata, body, _ = split_frontmatter(path.read_text())
    changed = False
    if not _string_value(metadata, "name"):
        metadata["name"] = name
        changed = True
    if not _string_value(metadata, "description"):
        metadata["description"] = f"Converted Claude skill {name}."
        changed = True
    if changed or not path.read_text().startswith("---\n"):
        path.write_text(build_frontmatter(metadata, body))


def _string_value(data: dict[str, Any], key: str) -> str | None:
    value = data.get(key)
    return value if isinstance(value, str) and value.strip() else None
